Added Hello World in Brainfuck
GDSC-SGGSCC/Hacktoberfest-22 pull request #38
Opened 2022-10-02 09:09 UTC by debxrshi

2022-10-02 13:18 UTC, reveurguy requested changes
i don't think this code is fine. Please check it and run it.

2022-10-03 06:48 UTC, debxrshi commented
Made the changes @reveurguy Ran it [via](https://copy.sh/brainfuck/)

2022-10-03 08:56 UTC, reveurguy commented
/hacktoberfest-accepted

2022-10-03 08:56 UTC, reveurguy commented
/label hacktoberfest-accepted

2022-10-03 08:56 UTC, merged